### ISSUE TITLE
fs browse function don'T work as expected on the root folders

### ISSUE THREAD

**Issue by sTiReBYJwlYSplALbjGz** [ps5-payload-dev/shsrv#1]
I have found a bug on fs browse function . 
going to PS5:8080/fs is working fine, but clicking on a folder (every one) trying to jump to PS5:8080/folder instead of   PS5:8080/fs/folder - if I add the prefix fs/ folder then it'S working fine also for subfolders

**Comment by john-tornblom** [comment]
Thank you for the report, but please put it in the correct repo: https://github.com/ps5-payload-dev/websrv
