### ISSUE TITLE
hbldr dont open devilutionx

### ISSUE THREAD

**Issue by gen04177** [ps5-payload-dev/shsrv#3]
Escape character is '^]'.

**Welcome to shsrv.elf running on pid 77, compiled Jun 24 2024 at 13:16:14**

Model:          xxxxxxxxxxx
S/N:               xxxxxxxxxxx
S/W:                4.500.005
SoC temp:               44 °C
CPU temp:               46 °C
CPU freq:             800 MHz

Type 'help' for a list of commands

/$ hbldr /data/homebrew/DevilutionX/devilutionx.elf --data-dir /data/homebrew/DevilutionX/ --diablo
[] W:\Build\J01795075\vsh\common_lib\lnc_util\src\lnc_util_ipc_client.cpp(382) getAppStatus: LNC_ISOK::0x80940004
pt_attach: File exists
/$

**Comment by john-tornblom** [comment]
For me it works fine:

```
/$ hbldr /data/homebrew/DevilutionX/devilutionx.elf --data-dir /data/homebrew/DevilutionX/ --diablo
[SceLncUtil] W:\Build\J01585706\vsh\common_lib\lnc_util\src\lnc_util_ipc_client.cpp(382) getAppStatus: LNC_ISOK::0x80940004
/$ ERROR: Error open error on file: fonts.mpq
ERROR: Error open error on file: DIABDAT.MPQ
ERROR: Error open error on file: hellfire.mpq
ERROR: Error open error on file: hfmonk.mpq
ERROR: Error open error on file: hfbard.mpq
ERROR: Error open error on file: hfbarb.mpq
ERROR: Error open error on file: hfmusic.mpq
ERROR: Error open error on file: hfvoice.mpq
INFO: Opening game controller for joystick at index 0
INFO: Opened game controller with mapping:
00008928536f6e79204475616c536500,Sony DualSense,a:b0,b:b1,x:b2,y:b3,back:b4,start:b6,leftstick:b7,rightstick:b8,leftshoulder:b9,rightshoulder:b10,dpup:b11,dpdown:b12,dpleft:b13,dpright:b14,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,crc:2889,platform:FreeBSD
```

I am guessing you are running some other payloads that are messing with your system, e.g., kstuff, which makes the system really slow

**Comment by gen04177** [comment]
I'm using shsrv and hbldr in the latest version, below is the list of active processes:

Link

/data/homebrew/Mednafen$ ps
     PID      PPID     PGID      SID      UID           AuthId    State     AppId    TitleId  Command

**Comment by gen04177** [comment]
Ask one of your contacts in 4.50 to do these tests, I believe the result will be the same...

**Comment by john-tornblom** [comment]
So you are not using k-stuff (the payload that allows you to run fake ps4 packages)? I dont think that payload appears as a new process

**Comment by gen04177** [comment]
I'm not using k-stuff, I just sent the hbldr payload and then shsrv and accessed it via telnet and tried to run diablo

**Comment by john-tornblom** [comment]
Alright, I do not have 4.50 so I cannot test it. I pushed a small update just now that sets errno when the ptrace syscall fails, should provide a more accurate error message for you now

**Comment by gen04177** [comment]
Give me a few minutes, I'll test...

**Comment by john-tornblom** [comment]
Wait, what hbldr are you sending? you don't need that at all. If it is one of mine earlier work, it has been deprecated in favor of websrv.

You just need shsrv, or websrv, nothing else

**Comment by gen04177** [comment]
Escape character is '^]'.

Welcome to shsrv.elf running on pid 77, compiled Jun 24 2024 at 13:58:32

Model:          xxxxxxxxx
S/N:               xxxxxxxxx
S/W:                4.500.005
SoC temp:               44 °C
CPU temp:               46 °C
CPU freq:             800 MHz

Type 'help' for a list of commands

/$ hbldr /data/homebrew/DevilutionX/devilutionx.elf --data-dir /data/homebrew/DevilutionX/ --diablo
[] W:\Build\J01795075\vsh\common_lib\lnc_util\src\lnc_util_ipc_client.cpp(382) getAppStatus: LNC_ISOK::0x80940004
pt_attach: error_code=0xffffffff
/$

**Comment by gen04177** [comment]
> Wait, what hbldr are you sending? you don't need that at all. If it is one of mine earlier work, it has been deprecated in favor of websrv.
> 
> You just need shsrv, or websrv, nothing else

In the latest version of shsrv is hbldr integrated? I always sent the separate hbldr payload before shsrv, compiled into the shsrv project...

**Comment by john-tornblom** [comment]
Yes, hbldr.elf should not be used at all, it was just an experimental payload.

**Comment by gen04177** [comment]
I understood. I restarted the PS5 and did a new test, now without sending the hbldr, just the shsrv:

Escape character is '^]'.

Welcome to shsrv.elf running on pid 76, compiled Jun 24 2024 at 13:58:32

Model:          xxxxxxxxxxxx
S/N:               xxxxxxxxxxxx
S/W:                4.500.005
SoC temp:               44 °C
CPU temp:               47 °C
CPU freq:             800 MHz

Type 'help' for a list of commands

/$ help
Builtin commands:
  authid
  browse
  cat
  cd
  chgrp
  chmod
  chown
  chroot
  cmp
  cp
  echo
  env
  exec
  exit
  export
  file
  find
  grep
  hbdbg
  hbldr
  help
  hexdump
  http2_get
  id
  kill
  launch
  ln
  ls
  mkdir
  mknod
  mount
  mv
  notify
  ps
  pwd
  rm
  rmdir
  sfocreate
  sfoinfo
  sleep
  stat
  sum
  sync
  sysctl
  touch
  umount
/$ hbldr /data/homebrew/DevilutionX/devilutionx.elf --data-dir /data/homebrew/DevilutionX/ --diablo
[] W:\Build\J01795075\vsh\common_lib\lnc_util\src\lnc_util_ipc_client.cpp(382) getAppStatus: LNC_ISOK::0x80940004
pt_attach: error_code=0xffffffff
